name: Build Mod
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: 21
        cache: 'gradle'
    - name: Build with Gradle
      run: gradle build --rerun-tasks
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs
